import './globals.css'
import type { Metadata } from 'next'
import { Rubik, Syne } from 'next/font/google'


const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'],
  variable: '--ff-rubik',
  display: 'swap'
});
const syne = Syne({
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'],
  variable: '--ff-syne',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${rubik.variable} ${syne.variable}`}>{children}</body>
    </html>
  )
}
